<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LinearPrecision.Worker</RootNamespace>
    <UserSecretsId>dotnet-LinearPrecision.Worker-6b68a344-55d4-41dd-8f8d-234fb4e09652</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinearPrecision.Api\LinearPrecision.Api.csproj" />
    <ProjectReference Include="..\LinearPrecision.Shared\LinearPrecision.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <!-- Background jobs -->
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <!-- Redis -->
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <!-- Logging -->
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

</Project>
