<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LinearPrecision.Worker</RootNamespace>
    <UserSecretsId>dotnet-LinearPrecision.Worker-6b68a344-55d4-41dd-8f8d-234fb4e09652</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinearPrecision.Api\LinearPrecision.Api.csproj" />
    <ProjectReference Include="..\LinearPrecision.Shared\LinearPrecision.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.*" />
    <!-- Background jobs -->
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.*" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.*" />
    <!-- Redis -->
    <PackageReference Include="StackExchange.Redis" Version="2.*" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.*" />
    <!-- Logging -->
    <PackageReference Include="Serilog.AspNetCore" Version="8.*" />
  </ItemGroup>

</Project>
